# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank
first_name: Martinez-Garcia
middle_name: Mario
last_name: 
contact_note: "You can even add a little note about which of these is the best way to reach you."
description: "A simple, whitespace theme for academics."
footer_text: "Powered by Jekyll with al-folio theme. Hosted by GitHub Pages."
keywords: jekyll, jekyll-theme, academic-website, portfolio-website
lang: en
icon: ⚛️

url: https://mariomartgarcia.github.io
baseurl: 
last_updated: false
back_to_top: true

# -----------------------------------------------------------------------------
# Theme
# -----------------------------------------------------------------------------

repo_theme_light: default
repo_theme_dark: dark

# -----------------------------------------------------------------------------
# RSS Feed
# -----------------------------------------------------------------------------

rss_icon: true

# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: false

# Dimensions
max_width: 930px

# -----------------------------------------------------------------------------
# Analytics and search engine verification
# -----------------------------------------------------------------------------

google_analytics: 
cronitor_analytics: 
pirsch_analytics: 
openpanel_analytics: 

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_google_analytics: false
enable_darkmode: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

markdown: kramdown
highlighter: rouge

# Includes & excludes
include: ["_pages", "_scripts"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - README.md
  - vendor
keep_files:
  - CNAME
  - .nojekyll

# Plug-ins
plugins:
  - jekyll-feed
  - jekyll-sitemap
